name: AzureMain Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az deployment group create \
              -l uksouth
              --resource-group njbappin \
              --template-file AzureTemplates/template.json \
              --parameters @AzureTemplates/parameters.json
